### ISSUE TITLE
error in _check_paper_page function and workaround

### ISSUE THREAD

**Issue by BrainofZedZed** [davidAlgis/zotero2SemanticScholar#2]
Hello,

Thanks for this tool! I started using Semantic Scholar but the lack of Zotero import do speed up the recommendation process was a bummer. This is exactly what I needed.

Out of the box, I had an error in the SemanticScholarScrapper, just within the _check_paper_page function. I'm on Windows 11, Python 3.11, in a fresh mambaforge install. It happened with different csv files with different paper data in it.

```
Traceback (most recent call last):
  File "C:\Users\boba4\mambaforge\envs\zz\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\boba4\Documents\GitHub\zotero2SemanticScholar\main.py", line 156, in _sendDataToSemanticscholar
    hasAddPaper = scrapper.scrap_paper_by_title(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\boba4\Documents\GitHub\zotero2SemanticScholar\SemanticScholarScrapper.py", line 92, in scrap_paper_by_title
    return self._check_paper_page(paper_title)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\boba4\Documents\GitHub\zotero2SemanticScholar\SemanticScholarScrapper.py", line 125, in _check_paper_page
    h1 = [h1 for h1 in h1_list if h1.get_attribute(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

I didn't immediately see how to solve the error, but since the function was just a safety check to make sure the right paper is imported, I just went around the code and forced the function to return true. Everything else worked perfectly and the papers have been accurate. 
If anyone else has this issue, hopefully this will be of use.

Thank you again David for this helpful tool!

**Comment by davidAlgis** [comment]
Hi, 
Thanks for your comment. 
I fixed this bug by updating the way I search the title.
These lines could be important depending on your input data. They ensure that the title found by scrapping corresponds to the title entered in the csv. 

Don't hesitate if you have any other problems.
