### ISSUE TITLE
Reading long csv bibliographies

### ISSUE THREAD

**Issue by joshisanonymous** [davidAlgis/zotero2SemanticScholar#6]
My Zotero library has about 1900 articles in it. When I try to read the CSV from the GUI, the "Reading library..." text remains at the bottom for a very long time (several hours at least). I can still send the data to Semantic Scholar while the text is present, but it appears simply search and add the articles to Semantic Scholar that had been successfully read by the time I press the button (e.g., I tried to read in 1900 but ended up with 700 in my Semantic Scholar library).

I'm not sure if this is a bug and it's getting hung up at some point or, given very many hours, it will eventually read the whole CSV and work as expected.

**Comment by davidAlgis** [comment]
Thanks for your feedback. I don't think it should take several hours for 1900 articles, I got about 400 and it takes only a few minutes.
Maybe you come across a bug. Could you copy the content of the `log.txt` at the root of the project ?
Moreover, I try it on my zotero library and I come across a bug that I solved. You can pull the repository, maybe it'll directly solve your problem.

**Comment by joshisanonymous** [comment]
I updated, but I hit the same limit. Here's my log.

[log.txt](https://github.com/davidAlgis/zotero2SemanticScholar/files/15156044/log.txt)

Python version is 3.10.1, used the reqs file for module versions. Win10 and 11 (tried on two different computers).

**Comment by davidAlgis** [comment]
Unfortunaly, I could not catch any error with your log. 
I updated the code to improve error detection, could you retry it and send me your log again ? If you prefer and if it's not sensible for you, you can send me the csv containing your bibliography at david.algis@tutamail.com so I can directly try on it.

**Comment by joshisanonymous** [comment]
It looks like that update fixed my issue. The terminal is showing #/1815 for items, which is about right for the number once misc bibliography items are removed, and the number of articles in my Semantic Scholar library has now exceeded 700 (the script is still adding more as I write this). The "Reading library" text in the GUI never goes away, though.

Thanks for your work here! Very helpful!

**Comment by davidAlgis** [comment]
Glad to know the problem solved. Thanks for your feedback !
